title: Jan Dokoupil
logo: /assets/img/profile_photo.png
description: Passionate aspiring Data Analyst with diverse experience in customer service, investment operations, and warehouse management. Proficient in Power BI and Excel, while learning SQL and Python. Committed to driving informed decisions through data analysis. Eager to contribute to dynamic teams.
#show_downloads: true
theme: jekyll-theme-minimal
