title: Jan Dokoupil
logo: /assets/img/profile_photo.png
description: Aspiring Data Analyst with hands-on experience in customer service, investment operations, and warehouse management. Proficient in Power BI, Excel, and Python, with growing expertise in SQL. Skilled in using data to drive informed decisions and eager to contribute to dynamic, data-driven teams.
#show_downloads: true
theme: jekyll-theme-minimal
