title: Jan Dokoupil
logo: /assets/img/profile_photo.png
description: Passionate Data Analyst with hands-on experience across customer service, investment operations, and warehouse management. Proficient in Power BI, Excel, and Python, with a growing expertise in SQL. Skilled in deriving actionable insights from data to support informed business decisions. Excited to apply my analytical expertise in dynamic, data-driven environments.
#show_downloads: true
theme: jekyll-theme-minimal
